# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created: Wed Aug 19 11:26:29 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1079, 870)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.vtkFrame_4 = QtGui.QFrame(self.centralwidget)
        self.vtkFrame_4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtkFrame_4.sizePolicy().hasHeightForWidth())
        self.vtkFrame_4.setSizePolicy(sizePolicy)
        self.vtkFrame_4.setAutoFillBackground(False)
        self.vtkFrame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.vtkFrame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.vtkFrame_4.setObjectName(_fromUtf8("vtkFrame_4"))
        self.gridLayout_5.addWidget(self.vtkFrame_4, 0, 0, 1, 1)
        self.controlFrame_4 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlFrame_4.sizePolicy().hasHeightForWidth())
        self.controlFrame_4.setSizePolicy(sizePolicy)
        self.controlFrame_4.setMinimumSize(QtCore.QSize(0, 40))
        self.controlFrame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.controlFrame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.controlFrame_4.setObjectName(_fromUtf8("controlFrame_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.controlFrame_4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_2 = QtGui.QWidget(self.controlFrame_4)
        self.widget_2.setMinimumSize(QtCore.QSize(20, 0))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout.addWidget(self.widget_2)
        self.labelT_11 = QtGui.QLabel(self.controlFrame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelT_11.setFont(font)
        self.labelT_11.setObjectName(_fromUtf8("labelT_11"))
        self.horizontalLayout.addWidget(self.labelT_11)
        self.textSliderValue_11 = QtGui.QLabel(self.controlFrame_4)
        self.textSliderValue_11.setMinimumSize(QtCore.QSize(31, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textSliderValue_11.setFont(font)
        self.textSliderValue_11.setObjectName(_fromUtf8("textSliderValue_11"))
        self.horizontalLayout.addWidget(self.textSliderValue_11)
        self.widget = QtGui.QWidget(self.controlFrame_4)
        self.widget.setMinimumSize(QtCore.QSize(25, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout.addWidget(self.widget)
        self.slider_11 = QtGui.QSlider(self.controlFrame_4)
        self.slider_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider_11.setOrientation(QtCore.Qt.Horizontal)
        self.slider_11.setObjectName(_fromUtf8("slider_11"))
        self.horizontalLayout.addWidget(self.slider_11)
        self.widget_3 = QtGui.QWidget(self.controlFrame_4)
        self.widget_3.setMinimumSize(QtCore.QSize(30, 0))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout.addWidget(self.widget_3)
        self.btn_play = QtGui.QPushButton(self.controlFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play.sizePolicy().hasHeightForWidth())
        self.btn_play.setSizePolicy(sizePolicy)
        self.btn_play.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_play.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_play.setFont(font)
        self.btn_play.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./lib/GUI/icons/mdi/ic_play_arrow_24px.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play.setIcon(icon)
        self.btn_play.setObjectName(_fromUtf8("btn_play"))
        self.horizontalLayout.addWidget(self.btn_play)
        self.btn_pause = QtGui.QPushButton(self.controlFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pause.sizePolicy().hasHeightForWidth())
        self.btn_pause.setSizePolicy(sizePolicy)
        self.btn_pause.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_pause.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_pause.setFont(font)
        self.btn_pause.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./lib/GUI/icons/mdi/ic_pause_24px.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pause.setIcon(icon1)
        self.btn_pause.setObjectName(_fromUtf8("btn_pause"))
        self.horizontalLayout.addWidget(self.btn_pause)
        self.btn_stop = QtGui.QPushButton(self.controlFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stop.sizePolicy().hasHeightForWidth())
        self.btn_stop.setSizePolicy(sizePolicy)
        self.btn_stop.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_stop.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_stop.setFont(font)
        self.btn_stop.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./lib/GUI/icons/mdi/ic_stop_24px.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stop.setIcon(icon2)
        self.btn_stop.setObjectName(_fromUtf8("btn_stop"))
        self.horizontalLayout.addWidget(self.btn_stop)
        self.btn_first = QtGui.QPushButton(self.controlFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_first.sizePolicy().hasHeightForWidth())
        self.btn_first.setSizePolicy(sizePolicy)
        self.btn_first.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_first.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_first.setFont(font)
        self.btn_first.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./lib/GUI/icons/mdi/ic_skip_previous_24px.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_first.setIcon(icon3)
        self.btn_first.setObjectName(_fromUtf8("btn_first"))
        self.horizontalLayout.addWidget(self.btn_first)
        self.btn_last = QtGui.QPushButton(self.controlFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_last.sizePolicy().hasHeightForWidth())
        self.btn_last.setSizePolicy(sizePolicy)
        self.btn_last.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_last.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_last.setFont(font)
        self.btn_last.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("./lib/GUI/icons/mdi/ic_skip_next_24px.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_last.setIcon(icon4)
        self.btn_last.setObjectName(_fromUtf8("btn_last"))
        self.horizontalLayout.addWidget(self.btn_last)
        self.btn_back = QtGui.QPushButton(self.controlFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back.sizePolicy().hasHeightForWidth())
        self.btn_back.setSizePolicy(sizePolicy)
        self.btn_back.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_back.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_back.setFont(font)
        self.btn_back.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("./lib/GUI/icons/mdi/back_24px.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon5)
        self.btn_back.setObjectName(_fromUtf8("btn_back"))
        self.horizontalLayout.addWidget(self.btn_back)
        self.btn_forward = QtGui.QPushButton(self.controlFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_forward.sizePolicy().hasHeightForWidth())
        self.btn_forward.setSizePolicy(sizePolicy)
        self.btn_forward.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_forward.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_forward.setFont(font)
        self.btn_forward.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("./lib/GUI/icons/mdi/forward_24px.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_forward.setIcon(icon6)
        self.btn_forward.setObjectName(_fromUtf8("btn_forward"))
        self.horizontalLayout.addWidget(self.btn_forward)
        self.btn_repeat = QtGui.QPushButton(self.controlFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_repeat.sizePolicy().hasHeightForWidth())
        self.btn_repeat.setSizePolicy(sizePolicy)
        self.btn_repeat.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_repeat.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_repeat.setFont(font)
        self.btn_repeat.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("./lib/GUI/icons/mdi/ic_repeat_24px.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_repeat.setIcon(icon7)
        self.btn_repeat.setObjectName(_fromUtf8("btn_repeat"))
        self.horizontalLayout.addWidget(self.btn_repeat)
        self.btn_plot = QtGui.QPushButton(self.controlFrame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_plot.sizePolicy().hasHeightForWidth())
        self.btn_plot.setSizePolicy(sizePolicy)
        self.btn_plot.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_plot.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_plot.setFont(font)
        self.btn_plot.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("./lib/GUI/icons/mdi/ic_equalizer_black_24dp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_plot.setIcon(icon8)
        self.btn_plot.setObjectName(_fromUtf8("btn_plot"))
        self.horizontalLayout.addWidget(self.btn_plot)
        self.widget_4 = QtGui.QWidget(self.controlFrame_4)
        self.widget_4.setMinimumSize(QtCore.QSize(30, 0))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout.addWidget(self.widget_4)
        self.gridLayout_5.addWidget(self.controlFrame_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1079, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHere = QtGui.QMenu(self.menubar)
        self.menuHere.setObjectName(_fromUtf8("menuHere"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuHere.addAction(self.actionExit)
        self.menubar.addAction(self.menuHere.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelT_11.setText(_translate("MainWindow", "T :", None))
        self.textSliderValue_11.setText(_translate("MainWindow", "0", None))
        self.menuHere.setTitle(_translate("MainWindow", "File", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

