# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui3_2.ui'
#
# Created: Mon Sep  7 19:28:44 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

# Standard library imports
import os
import sys

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1313, 968)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.vtkFrame = QtGui.QFrame(self.centralwidget)
        self.vtkFrame.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtkFrame.sizePolicy().hasHeightForWidth())
        self.vtkFrame.setSizePolicy(sizePolicy)
        self.vtkFrame.setAutoFillBackground(False)
        self.vtkFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.vtkFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.vtkFrame.setObjectName(_fromUtf8("vtkFrame"))
        self.verticalLayout.addWidget(self.vtkFrame)
        self.widget_3 = QtGui.QWidget(self.centralwidget)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelT_11 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.labelT_11.setFont(font)
        self.labelT_11.setObjectName(_fromUtf8("labelT_11"))
        self.horizontalLayout.addWidget(self.labelT_11)
        self.textSliderValue_11 = QtGui.QLabel(self.widget_3)
        self.textSliderValue_11.setMinimumSize(QtCore.QSize(31, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textSliderValue_11.setFont(font)
        self.textSliderValue_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textSliderValue_11.setObjectName(_fromUtf8("textSliderValue_11"))
        self.horizontalLayout.addWidget(self.textSliderValue_11)
        self.widget = QtGui.QWidget(self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(25, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout.addWidget(self.widget)
        self.slider_11 = QtGui.QSlider(self.widget_3)
        self.slider_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slider_11.setOrientation(QtCore.Qt.Horizontal)
        self.slider_11.setObjectName(_fromUtf8("slider_11"))
        self.horizontalLayout.addWidget(self.slider_11)
        self.widget_2 = QtGui.QWidget(self.widget_3)
        self.widget_2.setMinimumSize(QtCore.QSize(10, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1313, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHere = QtGui.QMenu(self.menubar)
        self.menuHere.setObjectName(_fromUtf8("menuHere"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtGui.QToolBar(MainWindow)
        self.toolBar_3.setObjectName(_fromUtf8("toolBar_3"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionPlay = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_play_arrow_24px.svg"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_play_arrow_24px.svg"))), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.actionPlay.setIcon(icon)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionPause = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_pause_24px.svg"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon1)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionStop = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_stop_24px.svg"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon2)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionFirst = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_skip_previous_24px.svg"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFirst.setIcon(icon3)
        self.actionFirst.setObjectName(_fromUtf8("actionFirst"))
        self.actionLast = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_skip_next_24px.svg"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLast.setIcon(icon4)
        self.actionLast.setObjectName(_fromUtf8("actionLast"))
        self.actionBack = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/back_24px.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBack.setIcon(icon5)
        self.actionBack.setObjectName(_fromUtf8("actionBack"))
        self.actionForward = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/forward_24px.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionForward.setIcon(icon6)
        self.actionForward.setObjectName(_fromUtf8("actionForward"))
        self.actionRepeat = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_repeat_24px.svg"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRepeat.setIcon(icon7)
        self.actionRepeat.setObjectName(_fromUtf8("actionRepeat"))
        self.actionPlot = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_equalizer_black_24dp.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlot.setIcon(icon8)
        self.actionPlot.setObjectName(_fromUtf8("actionPlot"))
        self.actionTime = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_schedule_black_24dp.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTime.setIcon(icon9)
        self.actionTime.setObjectName(_fromUtf8("actionTime"))
        self.actionCapacity = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_present_to_all_black_24dp.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCapacity.setIcon(icon10)
        self.actionCapacity.setObjectName(_fromUtf8("actionCapacity"))
        self.actionStart = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_assistant_photo_black_24dp.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon11)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionLabels = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_filter_2_black_24dp.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLabels.setIcon(icon12)
        self.actionLabels.setObjectName(_fromUtf8("actionLabels"))
        self.actionStLabels = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_filter_1_black_24dp.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStLabels.setIcon(icon13)
        self.actionStLabels.setObjectName(_fromUtf8("actionStLabels"))
        self.actionScalarBar = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_library_add_black_24dp.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScalarBar.setIcon(icon14)
        self.actionScalarBar.setObjectName(_fromUtf8("actionScalarBar"))
        self.actionAnnotations = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(os.path.join(os.path.dirname(__file__),"icons/mdi/ic_library_books_black_24dp.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnnotations.setIcon(icon15)
        self.actionAnnotations.setObjectName(_fromUtf8("actionAnnotations"))
        self.menuHere.addAction(self.actionExit)
        self.menubar.addAction(self.menuHere.menuAction())
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionTime)
        self.toolBar.addAction(self.actionCapacity)
        self.toolBar.addAction(self.actionPlot)
        self.toolBar_2.addAction(self.actionPlay)
        self.toolBar_2.addAction(self.actionPause)
        self.toolBar_2.addAction(self.actionStop)
        self.toolBar_2.addAction(self.actionFirst)
        self.toolBar_2.addAction(self.actionLast)
        self.toolBar_2.addAction(self.actionBack)
        self.toolBar_2.addAction(self.actionForward)
        self.toolBar_2.addAction(self.actionRepeat)
        self.toolBar_3.addAction(self.actionStLabels)
        self.toolBar_3.addAction(self.actionLabels)
        self.toolBar_3.addAction(self.actionScalarBar)
        self.toolBar_3.addAction(self.actionAnnotations)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.labelT_11.setText(_translate("MainWindow", "  Time:", None))
        self.textSliderValue_11.setText(_translate("MainWindow", "0", None))
        self.menuHere.setTitle(_translate("MainWindow", "File", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionPlay.setText(_translate("MainWindow", "play", None))
        self.actionPlay.setToolTip(_translate("MainWindow", "Play", None))
        self.actionPause.setText(_translate("MainWindow", "pause", None))
        self.actionPause.setToolTip(_translate("MainWindow", "Pause", None))
        self.actionStop.setText(_translate("MainWindow", "stop", None))
        self.actionStop.setToolTip(_translate("MainWindow", "Stop", None))
        self.actionFirst.setText(_translate("MainWindow", "first", None))
        self.actionFirst.setToolTip(_translate("MainWindow", "Go to the beggining of the visualization", None))
        self.actionLast.setText(_translate("MainWindow", "last", None))
        self.actionLast.setToolTip(_translate("MainWindow", "Go to the visualization end", None))
        self.actionBack.setText(_translate("MainWindow", "back", None))
        self.actionBack.setToolTip(_translate("MainWindow", "Back one time step", None))
        self.actionForward.setText(_translate("MainWindow", "forward", None))
        self.actionForward.setToolTip(_translate("MainWindow", "Forward one time step", None))
        self.actionRepeat.setText(_translate("MainWindow", "repeat", None))
        self.actionRepeat.setToolTip(_translate("MainWindow", "Play and repeat", None))
        self.actionPlot.setText(_translate("MainWindow", "plot", None))
        self.actionPlot.setToolTip(_translate("MainWindow", "Plot simulation data for the selected edge", None))
        self.actionTime.setText(_translate("MainWindow", "time", None))
        self.actionTime.setToolTip(_translate("MainWindow", "Display edge times", None))
        self.actionCapacity.setText(_translate("MainWindow", "capacity", None))
        self.actionCapacity.setToolTip(_translate("MainWindow", "Display edge capacities", None))
        self.actionStart.setText(_translate("MainWindow", "start", None))
        self.actionStart.setToolTip(_translate("MainWindow", "Display the network visualization scene", None))
        self.actionLabels.setText(_translate("MainWindow", "labels", None))
        self.actionLabels.setToolTip(_translate("MainWindow", "Show (or hide) non source/sink nodes labels", None))
        self.actionStLabels.setText(_translate("MainWindow", "stLabels", None))
        self.actionStLabels.setToolTip(_translate("MainWindow", "Show / hide source node and sink node labels", None))
        self.actionScalarBar.setText(_translate("MainWindow", "scalarBar", None))
        self.actionScalarBar.setToolTip(_translate("MainWindow", "Show / hide scalarbar", None))
        self.actionAnnotations.setText(_translate("MainWindow", "annotations", None))
        self.actionAnnotations.setToolTip(_translate("MainWindow", "Show / hide project info", None))

